// AUTH //
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_INFO = "GET_USER_INFO";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";
export const REGISTER_USER_LOADING = "REGISTER_USER_LOADING";
export const CREATE_NEW_USER = "CREATE_NEW_USER";

// POSTS
export const INIT_POST_LOADING = "INIT_POST_LOADING";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const GET_INIT_POSTS = "GET_INIT_POSTS";
export const POST_LOADING = "POST_LOADING";
export const GET_MORE_POSTS = "GET_MORE_POSTS";
export const CREATE_POST = "CREATE_POST";
export const GET_POST = "GET_POST";
export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_LOADING = "UPDATE_LOADING";
export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_LOADING = "DELETE_POST_LOADING";

// PATCH NOTES
export const INIT_PATCH_NOTES_LOADING = "INIT_PATCH_NOTES_LOADING";
export const UPDATE_PAGE_PATCH_NOTES = "UPDATE_PAGE_PATCH_NOTES";
export const GET_INIT_PATCH_NOTES = "GET_INIT_PATCH_NOTES";
export const PATCH_NOTES_LOADING = "PATCH_NOTES_LOADING";
export const GET_MORE_PATCH_NOTES = "GET_MORE_PATCH_NOTES";
export const CREATE_PATCH_NOTE = "CREATE_PATCH_NOTE";
export const GET_PATCH_NOTE = "GET_PATCH_NOTE";
export const UPDATE_PATCH_NOTE = "UPDATE_PATCH_NOTE";
export const UPDATE_PATCH_NOTE_LOADING = "UPDATE_PATCH_NOTE_LOADING";
export const DELETE_PATCH_NOTE = "DELETE_PATCH_NOTE";
export const DELETE_PATCH_NOTE_LOADING = "DELETE_PATCH_NOTE_LOADING";

// ARTICLES
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const EDIT_THUMBNAIL = "EDIT_THUMBNAIL";
export const GET_INIT_ARTICLES = "GET_INIT_ARTICLES";
export const INIT_ARTICLES_LOADING = "INIT_ARTICLES_LOADING";
export const ARTICLES_LOADING = "ARTICLES_LOADING";
export const UPDATE_PAGE_ART = "UPDATE_PAGE_ART";
export const GET_MORE_ARTICLES = "GET_MORE_ARTICLES";
export const GET_ARTICLE = "GET_ARTICLE";
export const GET_SEARCH_ARTICLES = "GET_SEARCH_ARTICLES";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const UPDATE_ARTICLE_LOADING = "UPDATE_ARTICLE_LOADING";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const DELETE_ARTICLE_LOADING = "DELETE_ARTICLE_LOADING";
export const GET_TOP_ARTICLE = "GET_TOP_ARTICLE";

// MESSAGES
export const GET_INIT_MESSAGES = "GET_INIT_MESSAGES";
export const INIT_MESSAGES_LOADING = "INIT_MESSAGES_LOADING";
export const MESSAGES_LOADING = "MESSAGES_LOADING";
export const GET_MORE_MESSAGES = "GET_MORE_MESSAGES";
export const UPDATE_PAGE_MSG = "UPDATE_PAGE_MSG";
export const GET_PREVIEW_MSG = "GET_PREVIEW_MSG"; // LOOK INTO IT, FIX BUG
export const MOVE_MESSAGE = "MOVE_MESSAGE";
export const MOVE_MESSAGE_SUCCESS = "MOVE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_MESSAGE_LOADING = "DELETE_MESSAGE_LOADING";
export const GET_MESSAGE = "GET_MESSAGE";
export const IS_READ_CHANGE = "IS_READ_CHANGE";

// TAGS
export const GET_TAGS = "GET_TAGS";

// TEAM
export const INIT_TEAM_LOADING = "INIT_TEAM_LOADING";
export const GET_TEAM_MEMBERS = "GET_TEAM_MEMBERS";
export const DELETE_TEAM_MEMBER = "DELETE_TEAM_MEMBER";
export const TEAM_LOADING = "TEAM_LOADING";

// MEMBER
export const GET_TEAM_MEMBER = "GET_TEAM_MEMBER";
export const SEND_RESET_PW_EMAIL = "SEND_RESET_PW_EMAIL";
export const RESET_PW_SUCCESS = "RESET_PW_SUCCESS";
export const UPDATE_MEMBER_AVATAR = "UPDATE_MEMBER_AVATAR";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_TEAM_MEMBER_INFO = "UPDATE_TEAM_MEMBER_INFO";
export const DELETE_USER_POST = "DELETE_USER_POST";
export const DELETE_TEAM_MEMBER_LOADING = "DELETE_TEAM_MEMBER_LOADING";
export const UPDATE_TEAM_MEMBER_LOADING = "UPDATE_TEAM_MEMBER_LOADING";
export const SEND_EMAIL_LOADING = "SEND_EMAIL_LOADING";
export const STOP_EMAIL_LOADING = "STOP_EMAIL_LOADING";

export const GET_USER_INIT_POSTS = "GET_USER_INIT_POSTS";
export const UPDATE_PAGE_UP = "UPDATE_PAGE_UP";
export const USER_POSTS_INIT_LOADING = "USER_POSTS_INIT_LOADING";
export const GET_MORE_USER_POSTS = "GET_MORE_USER_POSTS";
export const USER_POSTS_LOADING = "USER_POSTS_LOADING";

export const GET_USER_INIT_PATCH_NOTES = "GET_USER_INIT_PATCH_NOTES";
export const UPDATE_PAGE_UPA = "UPDATE_PAGE_UPA";
export const USER_PATCH_NOTES_INIT_LOADING = "USER_PATCH_NOTES_INIT_LOADING";
export const GET_MORE_USER_PATCH_NOTES = "GET_MORE_USER_PATCH_NOTES";
export const USER_PATCH_NOTES_LOADING = "USER_PATCH_NOTES_LOADING";
export const DELETE_USER_PATCH_NOTES = "DELETE_USER_PATCH_NOTES";

export const GET_USER_INIT_ARTICLES = "GET_USER_INIT_ARTICLES";
export const UPDATE_PAGE_UART = "UPDATE_PAGE_UART";
export const USER_ARTICLES_INIT_LOADING = "USER_ARTICLES_INIT_LOADING";
export const GET_MORE_USER_ARTICLES = "GET_MORE_USER_ARTICLES";
export const USER_ARTICLES_LOADING = "USER_ARTICLES_LOADING";

// MODALS
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

// ERRORS
export const ERROR_LOADING = "ERROR_LOADING";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
